

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace CSS.Database
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class CSSdbEntities : DbContext
{
    public CSSdbEntities()
        : base("name=CSSdbEntities")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<Clan> Clan { get; set; }

    public virtual DbSet<Player> Player { get; set; }

}

}

