
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace CSS.Database
{

using System;
    using System.Collections.Generic;
    
public partial class Player
{

    public long PlayerId { get; set; }

    public string Avatar { get; set; }

    public string GameObjects { get; set; }

}

}
