//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UCS.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stream
    {
        public long StreamId { get; set; }
        public string ReplayData { get; set; }
        public string BattleData { get; set; }
    }
}
